base_data_dir: ../blender-for-finger-segmentation/data2/
model_dir: models/segformer_b2
max_epoch: 1

data:
  zippity: ${node.loompa} # Value interpolation
  do: "oompa ${node.loompa}" # String interpolation
  waldo: ???
